# -*- coding: utf-8 -*-
"""10.025 (2025) CTD 1D Project - Code Template for Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtkS777wv1ccU1KhgxJMTc20bGhKmJ19

**Introduction**

We are providing this google colab template for two reasons.

1. **This Google Colab notebook is an online computing environment for you to work with various python libraries.** This prevents you from having to handle technical issues that you may encounter if you were working with these libraries on your local computer.

2. This notebook also guides you on the commands and steps necessary to work with these libraries.

### Step 0. Before you begin.

* We will use **ngrok**, a service that enables you to test your webapp on the internet. We will need to install the ```pyngrok``` library for this.

* We will use ```streamlit``` library that enables you to write python code to make the user interface for a webapp.


a. Sign up for an ngrok free account. https://dashboard.ngrok.com/


b. With your free **ngrok** account, login to the dashboard. Look for the section that says "Your Authtoken" from ngrok. Copy that string. https://dashboard.ngrok.com/get-started/your-authtoken

### Commands in this notebook.

You will notice that there are three kinds of commands in this notebook.

1. **Python statement** You will recognize them instantly e.g. ```from ngrok import ngrok```

2. **Terminal Commands** Such commands are prefixed with ```!``` e.g ```!ls -ltrc```. Behind each google colab notebook is a Linux-based operating system. If you have a MacBook, you are using such an operating system. You use these terminal commands to give instructions to the operating system to do something for you. We have given you all the necessary commands.

3. **Cell Magic Commands** Such commands are prefixed with ```%%``` e.g. ```%% writefile a.py```. Cell magic commands are a feature of Jupyter notebooks and helps you to manage the tasks in each code cell. We have given you all the necessary commands.

### Let's Begin

1. Install the ```pyngrok``` library. Run the cell below.

Note: in Jupyter, `!` means run this command in the shell (i.e. Terminal in Mac/Linux, Anaconda Prompt in Windows).
"""

!pip install pyngrok

"""2. Paste Your Authtoken over ```<your authoken here>``` and remove only the ```#```

**Example**. ```!ngrok authtoken 40AbCdEEfffgggghhkkkpppqqrrranyattttt```
"""

#!ngrok authtoken <your authtoken here>

"""3. Run the cell below to ensure that your ngrok library is the most updated.

- You only need to run this cell once at the start of each session. After that, comment out the python commands in this cell.
"""

from pyngrok import ngrok
#ngrok.update()

"""4. Run the following cell to install the  ```streamlit``` library."""

!pip install streamlit -q

"""### Step 1. Build a simple webapp by writing code.

1. Functions that do calculations for your app should be stored in a file for the code in **mylibrary.py** to call. Here we store one function in a file called **mylibrary.py**.

Note: In Jupyter, we use `%%` to run *magic commands* for the cell. For example, we can add `%%timeit` at the start of a cell to check how long our code takes to run. In the cell below, `%%writefile` puts our cell code into the specified file.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mylibrary.py
# 
# def calculate_total( oranges, apples):
#     return 2*oranges + 3*apples
# 
# def plastic_bags_price(bags):
#     """one bag 0.1, two bags 0.4, three bags 0.9 """
#     return 0.1*bags*bags

"""2. Your ```streamlit``` webapp is usually stored in a python file called **app.py**. The first line in this cell ```%%writefile app.py``` creates this python file which contains all the code in this file.

- Study the statements below and see how each python statement creates a different widget. Also, observe the role of ```st.session_state``` and how it is linked to the ```key``` attribute of each widget.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import mylibrary
# 
# st.write("Hello!")
# st.text_input("Enter the quantity of African Oranges $2 each", key="oranges")
# st.number_input("Enter the quantity of Fuji Apples $3 each", min_value=0, max_value=10, step=1, key="apples")
# st.slider("How many plastic bags do you want", min_value=0, max_value=3, step=1, key="bags")
# bags_cost = mylibrary.plastic_bags_price(st.session_state.bags)
# st.write("Your plastic bags will cost $" + str(bags_cost))
# 
# if st.button('Get Total'):
#     st.write('Calculating Your Total ...')
#     oranges = int(st.session_state.oranges)
#     apples = int(st.session_state.apples)
#     result = mylibrary.calculate_total(oranges, apples)
#     total = bags_cost + result
#     st.write('Please pay {:.2f}'.format(total))
# else:
#     st.write('Please Key In The Quantity')

"""3. The files are stored somewhere on your google account's filesystem. To see the files, run the following terminal commands.

```pwd``` - **p**rint **w**orking **d**irectory
"""

!pwd

"""```ls``` - **l**ist content**s** . The ```-ltrc``` flag specifies how the contents of the folder are displayed."""

!ls -ltrc

"""Write python code to open the file **mylibrary.py** and display its contents. You learn how to do this in **Lesson 6**."""

with open('mylibrary.py') as f:
  print(f.read())

"""Write similar code to display the contents of **app.py**."""



"""3. Now we have start a streamlit server to *serve* our webpage to users.

- In the below command:
  - `streamlit run app.py` tells streamlit to start a server.
  - `--server.port 5011` starts it on port 5011 (the `--` is for options).
  - `nohup` (no hang up) makes sure that the server doesn't die when we close the Colab connection
  - `&` sends the command to the background so the notebook doesn't wait for the server to finish (since the server is supposed to keep running)
"""

!nohup streamlit run app.py --server.port 5011 &

"""4. Next, we run some ngrok functions so that this server can be accessed on the internet. You should see a URL that you can click on. Click it - that's your webapp and interact with it to see that it works as it should."""

from pyngrok import ngrok

# Start ngrok tunnel to expose the Streamlit server
ngrok_tunnel = ngrok.connect(addr='5011', proto='http', bind_tls=True)

# Print the URL of the ngrok tunnel
print(' * Tunnel URL:', ngrok_tunnel.public_url)

"""5. Make a change to any string in ```app.py``` and run the cell e.g. change ```African``` to any other word. On your webapp, you should see a prompt for you to reload. Follow it and see that the change is made.

6. Note that the free service for ```ngrok``` means that your URL in step 4 is not permanent. Once it is no longer accessible, go to the top of your notebook and select **Restart Session and Run All**.

7. You may also encounter errors displaying the URL in Step 4. If this happens, go to https://dashboard.ngrok.com/agents, click on the agent shown (look for the three dots) and select delete.

### Step 2. Learn on your own.

Now that you can build your own webapp, learn about the various widgets available in Streamlit and experiment with them.
https://docs.streamlit.io/develop/api-reference/widgets

### Alternative: You could choose to run this project locally on your laptop.

If you just want to run this on your local machine, it's easier and you don't need `ngrok`.

1. From your shell (Terminal / Anaconda Prompt), install streamlit using `pip install streamlit`
2. Create a project folder for the `.py` files in this project
3. Put the template code from Step 1.1 in `mylibrary.py`
4. Put the template code from Step 1.2 in `app.py`
5. Edit the files as you wish
6. To start streamlit, open your shell (Terminal / Anaconda Prompt) and go to your project folder. You can use `cd xxxx` to **c**hange **d**irectory to folder `xxxx`. To go up one directory level, use `cd ..`
7. When you are in the project folder, run `streamlit run app.py`
8. The server should start (on your computer) and take you to the webpage in your browser.

### Resources used

The writer of this assignment spoke to Prof Kenny Lu who pointed him to the **ngrok** service and shared some resources used in another SUTD course. The writer then read this [article from medium.com](https://medium.com/@mrcoffeeai/running-streamlit-on-google-colab-with-pyngrok-24895581df43) and used the code given. The writer also looked at the Streamlit documentation, in the [section for beginners](https://docs.streamlit.io/get-started/fundamentals/main-concepts). Faculty and UTAs teaching CTD helped to give feedback.

---------
>
> Use this notebook as a template for your project. You may add cells if you have more code to write. Do not delete any cells, every aspect is important.
>
---------
"""